# This is workflow job to execute JSON-compare of matillion objects

name: JSON-compare

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this is the job that creates the json-difference
  compare:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checout main
        uses: actions/checkout@v4
        with:
          path: main
          
      - name: 'Checkout PR branch'
        uses: actions/checkout@v4
        with:
          ref:  ${{ github.event.pull_request.head.sha }}
          path: pull-request
          
      # Set up Go for jd command funtionality
      - name: Set up GO
        uses: actions/setup-go@v4
        with:
            go-version: '1.20'

      # Install jd command funtionality
      - name: Install json-diff
        run:
         go install github.com/josephburnett/jd@latest
         
      # Gets all diff files
      - name: Initialize diff_files Enviornment variable
        run: |
          cd ${{ github.workspace }}/pull-request/ROOT/
          diff_files=$(git log --name-only)
          # for troubleshooting use
          # echo "This is initialization of enviornment variable: $diff_files"
          
      - name: Create file to manipulate text to achieve a list of files with change
        run: |
          echo "$diff_files" > files.txt
          echo "Initialization of files.txt"
          echo $(cat files.txt)
          
      - name: Manipulate text file to achieve a list of files with change and no extra header rows and load into BASH variable
        run: |
          files=$(sed '1,4d' files.txt)          
          echo "Removed unnecissary rows: ${files}"

      - name: Update the files variable(BASH variable) and add commas and remove line feeds to the list of files within
        run: |
          # ${parameter/pattern/string} replacement where:
          # parameter is the original string
          # pattern is the pattern to find and replace
          # string is the replacement value
          
          # Transformation commas
          files=${files/".TRANSFORMATION"/".TRANSFORMATION,"}
          echo "Update of Transformations in variable files: ${files}"
          
          # Orchestration commas
          files=${files/".ORCHESTRATION"/".ORCHESTRATION,"}
          echo "Update of Orchestrations in variable files: ${files}"

          # Remove line feeds
          files=${files/"\n"/""}
          echo "Update of Orchestrations in variable files: ${files}"
          
      - name: Initialize enviornment variable with updated list with commas
        run: |
          # get list into envoirnment variable
          # DIFF_FILES=$(${files}) >> $GITHUB_ENV
          DIFF_FILES_LIST=$(${files}) >> $GITHUB_ENV

      # # set s2 credentials 
      # - name: Configure secret
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      #     aws-bucket: ${{ secrets.S3_BUCKET_NAME }}
      #     file-path: ./mati-json-diffs/
          
      # Calls json diff action
      - name: Call json-diff
        run: |
          for i in $DIFF_FILES_LIST; do 
            echo ${i}
            b =${i##*/}
            echo ${b}
            DIFF_RESULTS=jd "/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/main/${i}" "/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/pull-request/${i}"
            echo $DIFF_RESULTSS
          done
          # jd "/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/main/ROOT/Fact Financial Metrics/Fact_Financial_Metrics.ORCHESTRATION" 
          # "/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/pull-request/ROOT/Fact Financial Metrics/Fact_Financial_Metrics.ORCHESTRATION"
      
